### ISSUE TITLE
请求添加使用wepy的开源项目：Scrum敏捷估算

### ISSUE THREAD

**Issue by yociduo** [aben1188/awesome-wepy#47]
基于wepy的敏捷估算工具

https://github.com/yociduo/scrum-planning-poker

**Comment by aben1188** [comment]
> 基于wepy的敏捷估算工具
> 
> https://github.com/yociduo/scrum-planning-poker

麻烦提交一个pr给我吧，谢谢！

**Comment by yociduo** [comment]
@aben1188 好了
